'use client';

import { useEffect, useState } from 'react';

type Lead = { id: string; name: string; company?: string; email: string; status: string; source?: string; campaign_name?: string; lead_score?: number; is_high_conversion_probable?: boolean; marketing_notes?: string; assigned_marketing_id?: string | null };
type Employee = { id: string; first_name: string; last_name: string; email: string };

export default function MarketingDashboard() {
  const [leads, setLeads] = useState<Lead[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); const [l, e] = await Promise.all([fetch('/api/department/leads?department=Marketing'), fetch('/api/department/employees?department=Marketing')]); const lj = await l.json(); const ej = await e.json(); setLeads(lj.data ?? []); setEmployees(ej.data ?? []); setLoading(false); };
  useEffect(() => { load(); }, []);
  const update = async (leadId: string, action: string, extra: Record<string, unknown> = {}) => { const r = await fetch('/api/department/leads', { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ leadId, action, ...extra }) }); const j = await r.json(); setMessage(r.ok ? 'Lead updated successfully.' : j.error); if (r.ok) load(); };
  return <main className="p-6 space-y-6"><header><h1 className="text-2xl font-extrabold">Marketing Workspace</h1><p className="text-sm text-slate-500">Lead intake, qualification, assignment and Sales handover.</p></header>{message && <div className="rounded-xl bg-slate-900 text-white px-4 py-3 text-sm">{message}</div>}<section className="grid grid-cols-3 gap-4"><div className="bg-white border rounded-2xl p-5"><b>{leads.length}</b><p className="text-xs text-slate-500">Marketing leads</p></div><div className="bg-white border rounded-2xl p-5"><b>{leads.filter(x=>x.is_high_conversion_probable).length}</b><p className="text-xs text-slate-500">High-conversion probable</p></div><div className="bg-white border rounded-2xl p-5"><b>{employees.length}</b><p className="text-xs text-slate-500">Marketing employees</p></div></section><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b font-bold">Lead Queue</div>{loading ? <div className="p-6">Loading…</div> : <div className="divide-y">{leads.map(lead => <article key={lead.id} className="p-4 grid grid-cols-[1fr_auto] gap-4"><div><div className="font-bold">{lead.name} <span className="text-xs font-normal text-slate-500">{lead.company}</span></div><div className="text-xs text-slate-500">{lead.email} · {lead.source ?? 'Website'} · {lead.campaign_name ?? 'No campaign'}</div><p className="text-sm mt-2">{lead.marketing_notes || 'No marketing notes yet.'}</p></div><div className="flex flex-col gap-2 items-end"><select value={lead.assigned_marketing_id ?? ''} onChange={e=>update(lead.id,'marketing_assign',{employeeId:e.target.value||null})} className="border rounded-lg p-2 text-xs"><option value="">Unassigned</option>{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select><label className="text-xs flex items-center gap-2"><input type="checkbox" checked={!!lead.is_high_conversion_probable} onChange={e=>update(lead.id,'marketing_update',{isHighConversion:e.target.checked})}/> High conversion</label>{lead.is_high_conversion_probable && <button onClick={()=>update(lead.id,'transfer_to_sales')} className="px-3 py-2 rounded-lg bg-teal-600 text-white text-xs font-bold">Transfer to Sales</button>}</div></article>)}</div>}</section></main>;
}
