'use client';
import { useEffect,useMemo,useState } from 'react';
import { Plus,Search,RefreshCw,Trash2,UserCheck,X,Save } from 'lucide-react';

type Lead={id:string;name:string;email:string;phone?:string;company?:string;source?:string;status:string;value?:number;lead_score?:number;lead_temperature?:string;assigned_department?:string;assigned_employee_id?:string|null;assigned_sales_id?:string|null;assigned_marketing_id?:string|null;follow_up_date?:string|null;sales_pipeline_stage?:string;marketing_pipeline_stage?:string;notes?:string};
type Employee={id:string;first_name:string;last_name:string;email:string;department_type:string;user_role:string;status:string};
const statuses=['New','Assigned','Contacted','Follow-up','Qualified','Converted','Disqualified'];
const stages=['Qualification','Discovery','Proposal','Negotiation','Closed Won','Closed Lost'];

export default function LeadsPage(){
 const [leads,setLeads]=useState<Lead[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[department,setDepartment]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<Lead|null>(null),[saving,setSaving]=useState(false),[canManage,setCanManage]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const me=await fetch('/api/auth/me',{cache:'no-store'});if(!me.ok)throw new Error('Session expired');const md=await me.json();const manage=!!md.isAdmin||['Admin','DeptHead','Manager'].includes(md.userRole);setCanManage(manage);const params=new URLSearchParams();if(search)params.set('search',search);if(status)params.set('status',status);if(department)params.set('department',department);const [lr,er]=await Promise.all([fetch(`/api/leads?${params}`,{cache:'no-store'}),manage?fetch('/api/department/employees?department='+(md.department||'Sales')):Promise.resolve(null)]);const lj=await lr.json();if(!lr.ok)throw new Error(lj.error||'Unable to load leads');setLeads(lj.data||[]);if(er){const ej=await er.json();setEmployees(ej.data||[])} }catch(e){setError(e instanceof Error?e.message:'Unable to load leads')}finally{setLoading(false)}};
 useEffect(()=>{load()},[status,department]);
 useEffect(()=>{const t=setTimeout(load,350);return()=>clearTimeout(t)},[search]);
 const save=async()=>{if(!editing)return;setSaving(true);const r=await fetch('/api/leads',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});const j=await r.json();if(!r.ok)setError(j.error||'Save failed');else{setEditing(null);await load()}setSaving(false)};
 const remove=async(id:string)=>{if(!confirm('Delete this lead?'))return;const r=await fetch(`/api/leads?id=${id}`,{method:'DELETE'});const j=await r.json();if(!r.ok)setError(j.error||'Delete failed');else load()};
 const assign=async(lead:Lead,employeeId:string)=>{const r=await fetch('/api/leads/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({leadId:lead.id,assignedDepartment:lead.assigned_department||department||'Sales',assignedEmployeeId:employeeId||null})});const j=await r.json();if(!r.ok)setError(j.error||'Assignment failed');else load()};
 const totals=useMemo(()=>statuses.map(s=>[s,leads.filter(l=>l.status===s).length] as const),[leads]);
 return <main className="p-3 sm:p-5 lg:p-6 space-y-5 max-w-[1800px] mx-auto"><header className="flex flex-col sm:flex-row gap-3 sm:items-center"><div><h1 className="text-2xl font-extrabold">Leads Management</h1><p className="text-sm text-slate-500">Central lead database, ownership, activities and pipeline control.</p></div><div className="sm:ml-auto flex gap-2"><button onClick={()=>setEditing({id:'',name:'',email:'',status:'New',assigned_department:department||'Sales'})} className="px-4 py-2.5 rounded-xl bg-teal-600 text-white text-xs font-bold flex items-center gap-2"><Plus className="w-4 h-4"/>New Lead</button><button onClick={load} className="p-2.5 rounded-xl bg-white border" aria-label="Refresh"><RefreshCw className="w-4 h-4"/></button></div></header>
 <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">{totals.map(([s,n])=><button key={s} onClick={()=>setStatus(status===s?'':s)} className={`p-3 rounded-xl border text-left bg-white ${status===s?'ring-2 ring-teal-500':''}`}><div className="text-[10px] text-slate-500">{s}</div><b className="text-xl">{n}</b></button>)}</div>
 <section className="bg-white border rounded-2xl p-3 flex flex-col md:flex-row gap-2"><div className="flex-1 flex items-center bg-slate-50 rounded-xl px-3"><Search className="w-4 h-4 text-slate-400 mr-2"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, company, email or phone…" className="w-full bg-transparent outline-none p-2 text-sm"/></div><select value={department} onChange={e=>setDepartment(e.target.value)} className="border rounded-xl p-2 text-sm"><option value="">All departments</option><option>Marketing</option><option>Sales</option><option>Operations</option><option>HR</option><option>Finance</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-xl p-2 text-sm"><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></section>
 {error&&<div className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-sm">{error}</div>}
 <section className="bg-white border rounded-2xl overflow-hidden">{loading?<div className="p-10 text-center text-slate-500">Loading leads…</div>:leads.length===0?<div className="p-12 text-center text-slate-500">No leads found.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3 text-left">Lead</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Owner</th><th className="p-3 text-left">Pipeline</th><th className="p-3 text-left">Score</th><th className="p-3 text-left">Follow-up</th><th className="p-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{leads.map(l=>{const owner=l.assigned_sales_id||l.assigned_marketing_id||l.assigned_employee_id;return <tr key={l.id} className="hover:bg-slate-50"><td className="p-3"><b>{l.name}</b><div className="text-xs text-slate-500">{l.company||'—'} · {l.email}</div></td><td className="p-3"><span className="px-2 py-1 rounded-full bg-slate-100 text-xs">{l.status}</span></td><td className="p-3">{canManage?<select value={owner||''} onChange={e=>assign(l,e.target.value)} className="border rounded-lg p-2 text-xs"><option value="">Unassigned</option>{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select>:<span className="text-xs">Assigned to you</span>}</td><td className="p-3"><select value={l.sales_pipeline_stage||'Qualification'} onChange={e=>setEditing({...l,sales_pipeline_stage:e.target.value})} className="border rounded-lg p-2 text-xs"><option value="Qualification">Qualification</option>{stages.slice(1).map(s=><option key={s}>{s}</option>)}</select></td><td className="p-3">{l.lead_score??0} <span className="text-xs text-slate-400">{l.lead_temperature||''}</span></td><td className="p-3 text-xs">{l.follow_up_date?new Date(l.follow_up_date).toLocaleString():'—'}</td><td className="p-3 text-right"><div className="flex justify-end gap-1"><button onClick={()=>setEditing(l)} className="px-3 py-2 rounded-lg border text-xs flex items-center gap-1"><UserCheck className="w-3 h-3"/>Edit</button>{canManage&&<button onClick={()=>remove(l.id)} className="p-2 rounded-lg border text-rose-600" aria-label="Delete"><Trash2 className="w-4 h-4"/></button>}</div></td></tr>})}</tbody></table></div>}</section>
 {editing&&<div className="fixed inset-0 z-[100] bg-slate-900/50 p-3 sm:p-6 flex items-center justify-center"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto p-5 space-y-4"><div className="flex items-center"><h2 className="font-extrabold text-lg">{editing.id?'Edit Lead':'Create Lead'}</h2><button onClick={()=>setEditing(null)} className="ml-auto p-2"><X/></button></div><div className="grid sm:grid-cols-2 gap-3">{([['name','Name'],['email','Email'],['company','Company'],['phone','Phone'],['source','Source'],['lead_score','Lead Score']] as const).map(([k,label])=><label key={k} className="text-xs font-semibold">{label}<input value={String(editing[k]??'')} onChange={e=>setEditing({...editing,[k]:k==='lead_score'?Number(e.target.value):e.target.value})} className="mt-1 w-full border rounded-xl p-2.5 font-normal"/></label>)}<label className="text-xs font-semibold">Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})} className="mt-1 w-full border rounded-xl p-2.5">{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs font-semibold">Temperature<select value={editing.lead_temperature||'Warm'} onChange={e=>setEditing({...editing,lead_temperature:e.target.value})} className="mt-1 w-full border rounded-xl p-2.5"><option>Hot</option><option>Warm</option><option>Cold</option></select></label><label className="text-xs font-semibold sm:col-span-2">Follow-up<input type="datetime-local" value={editing.follow_up_date?new Date(editing.follow_up_date).toISOString().slice(0,16):''} onChange={e=>setEditing({...editing,follow_up_date:e.target.value?new Date(e.target.value).toISOString():null})} className="mt-1 w-full border rounded-xl p-2.5"/></label><label className="text-xs font-semibold sm:col-span-2">Notes<textarea value={editing.notes||''} onChange={e=>setEditing({...editing,notes:e.target.value})} className="mt-1 w-full border rounded-xl p-2.5 min-h-24"/></label></div><div className="flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="px-4 py-2 rounded-xl border">Cancel</button><button onClick={save} disabled={saving} className="px-4 py-2 rounded-xl bg-teal-600 text-white font-bold flex gap-2 items-center"><Save className="w-4 h-4"/>{saving?'Saving…':'Save Lead'}</button></div></div></div>}
 </main>
}
