import { NextResponse } from 'next/server';
import { getAuthContext, isDepartmentHead } from '@/lib/department-auth';
import { supabase } from '@/lib/supabase';
const writable=['name','email','first_name','last_name','display_name','phone','mobile_number','whatsapp_number','company','company_website','job_title','department','country','emirate_state','city','address','source','sub_source','campaign_name','campaign_id','requirements','requirement_description','main_pain_point','expected_solution','interested_service','sub_service','product_category','estimated_budget','expected_purchase_date','project_timeline','urgency','quantity','project_location','existing_vendor','competitors_considered','additional_requirements','notes','marketing_notes','sales_notes','lead_score','lead_temperature','follow_up_date','call_scheduled_at','next_action','next_action_at','preferred_contact_method','preferred_language','contact_time_preference','status','assigned_department','assigned_dept_head_id','assigned_employee_id','assigned_marketing_id','assigned_sales_id','is_high_conversion_probable','conversion_probability','marketing_pipeline_stage','sales_pipeline_stage','branch','team','payment_status','approval_status'] as const;
const assignmentFields=['assigned_employee_id','assigned_sales_id','assigned_marketing_id','assigned_dept_head_id'];const statuses=['New','Assigned','Contacted','Follow-up','Qualified','Converted','Disqualified'];
const manage=(c:Awaited<ReturnType<typeof getAuthContext>>)=>c.isAdmin||isDepartmentHead(c);const owns=(c:Awaited<ReturnType<typeof getAuthContext>>,l:any)=>!!c.employeeId&&[l.assigned_employee_id,l.assigned_sales_id,l.assigned_marketing_id].includes(c.employeeId);const clean=(b:any,allow:boolean)=>Object.fromEntries(writable.filter(k=>k in b&&(allow||!assignmentFields.includes(k))).map(k=>[k,b[k]===''?null:b[k]]));
async function auth(){const c=await getAuthContext();if(!c.employeeId&&!c.isAdmin)throw new Error('Unauthorized');return c;}
async function create(c:Awaited<ReturnType<typeof getAuthContext>>,b:any){const d=clean(b,manage(c));if(!d.name||!d.email)throw new Error('Name and email are required');if(d.status&&!statuses.includes(String(d.status)))throw new Error('Invalid lead status');if(!manage(c)){d.assigned_employee_id=c.employeeId;d.assigned_department=c.department;d.status='Assigned'}d.last_activity_at=new Date().toISOString();const {data,error}=await supabase.from('leads').insert(d).select('*').single();if(error)throw error;await supabase.from('lead_activities').insert({lead_id:data.id,employee_id:c.employeeId,department:c.department,activity_type:'created',details:'Lead created'});return data;}
export async function GET(request:Request){try{const c=await auth(),p=new URL(request.url).searchParams;let q=supabase.from('leads').select('*').order('last_activity_at',{ascending:false});if(!manage(c))q=q.or(`assigned_employee_id.eq.${c.employeeId},assigned_sales_id.eq.${c.employeeId},assigned_marketing_id.eq.${c.employeeId}`);if(p.get('status'))q=q.eq('status',p.get('status')!);if(p.get('department'))q=q.eq('assigned_department',p.get('department')!);if(p.get('assignedEmployeeId'))q=q.eq('assigned_employee_id',p.get('assignedEmployeeId')!);if(p.get('search')){const s=p.get('search')!.replace(/[%_]/g,'');if(s)q=q.or(`name.ilike.%${s}%,email.ilike.%${s}%,company.ilike.%${s}%,phone.ilike.%${s}%`)}const {data,error}=await q;if(error)throw error;return NextResponse.json({data:data??[]})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to load leads'},{status:e instanceof Error&&e.message==='Unauthorized'?401:500})}}
export async function POST(request:Request){try{const c=await auth(),data=await create(c,await request.json());return NextResponse.json({success:true,data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Create failed'},{status:500})}}
export async function PATCH(request:Request){try{const c=await auth(),b=await request.json(),id=String(b.leadId||'');if(!id){const data=await create(c,b);return NextResponse.json({success:true,data},{status:201})}const {data:lead,error:find}=await supabase.from('leads').select('*').eq('id',id).single();if(find||!lead)return NextResponse.json({error:'Lead not found'},{status:404});if(!manage(c)&&!owns(c,lead))return NextResponse.json({error:'Forbidden'},{status:403});const d=clean(b,manage(c));delete d.leadId;if(d.status&&!statuses.includes(String(d.status)))return NextResponse.json({error:'Invalid lead status'},{status:400});if(d.conversion_probability!==undefined)d.conversion_probability=Math.max(0,Math.min(100,Number(d.conversion_probability)||0));if(d.lead_score!==undefined)d.lead_score=Math.max(0,Math.min(100,Number(d.lead_score)||0));d.last_activity_at=new Date().toISOString();if(d.status==='Contacted')d.last_contacted_at=new Date().toISOString();if(d.status==='Qualified'&&!lead.qualified_at)d.qualified_at=new Date().toISOString();if(d.status==='Converted')d.converted_at=new Date().toISOString();const {data,error}=await supabase.from('leads').update(d).eq('id',id).select('*').single();if(error)throw error;await supabase.from('lead_activities').insert({lead_id:id,employee_id:c.employeeId,department:c.department,activity_type:'updated',details:JSON.stringify(Object.keys(d))});return NextResponse.json({success:true,data})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Update failed'},{status:500})}}
export async function DELETE(request:Request){try{const c=await auth();if(!manage(c))return NextResponse.json({error:'Only administrators can delete leads'},{status:403});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({error:'id is required'},{status:400});const {error}=await supabase.from('leads').delete().eq('id',id);if(error)throw error;return NextResponse.json({success:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Delete failed'},{status:500})}}
