'use client';

import { useEffect, useMemo, useState } from 'react';
type Lead = { id:string; name:string; company?:string; email:string; status:string; sales_notes?:string; follow_up_date?:string|null; call_scheduled_at?:string|null; assigned_sales_id?:string|null };
type Employee = {id:string;first_name:string;last_name:string};
export default function SalesDashboard(){ const [leads,setLeads]=useState<Lead[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[filter,setFilter]=useState<'all'|'today'>('all'),[loading,setLoading]=useState(true),[saving,setSaving]=useState('');
 const load=async()=>{setLoading(true);const q=filter==='today'?'&today=true':'';const [l,e]=await Promise.all([fetch('/api/department/leads?department=Sales'+q),fetch('/api/department/employees?department=Sales')]);const lj=await l.json(),ej=await e.json();setLeads(lj.data??[]);setEmployees(ej.data??[]);setLoading(false)};useEffect(()=>{load()},[filter]);
 const save=async(id:string,extra:Record<string,unknown>)=>{setSaving(id);await fetch('/api/department/leads',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({leadId:id,action:'sales_update',...extra})});setSaving('');load()};
 const tasks=useMemo(()=>leads.filter(l=>l.call_scheduled_at||l.follow_up_date),[leads]);
 return <main className="p-6 space-y-6"><header><h1 className="text-2xl font-extrabold">Sales Pipeline</h1><p className="text-sm text-slate-500">Transferred high-conversion leads, ownership, pipeline activity and daily follow-ups.</p></header><div className="flex gap-2"><button onClick={()=>setFilter('all')} className={`px-4 py-2 rounded-lg text-xs font-bold ${filter==='all'?'bg-teal-600 text-white':'bg-white border'}`}>All transferred leads</button><button onClick={()=>setFilter('today')} className={`px-4 py-2 rounded-lg text-xs font-bold ${filter==='today'?'bg-teal-600 text-white':'bg-white border'}`}>Today’s tasks</button><span className="ml-auto text-sm text-slate-500">{tasks.length} scheduled</span></div><section className="bg-white border rounded-2xl overflow-hidden">{loading?<div className="p-6">Loading…</div>:leads.length===0?<div className="p-10 text-center text-slate-500">No transferred leads match this filter.</div>:<div className="divide-y">{leads.map(l=><article key={l.id} className="p-5 space-y-3"><div className="flex justify-between"><div><h2 className="font-bold">{l.name} <span className="font-normal text-slate-500">{l.company}</span></h2><p className="text-xs text-slate-500">{l.email}</p></div><span className="text-xs px-2 py-1 rounded-full bg-teal-50 text-teal-700">{l.status}</span></div><div className="grid md:grid-cols-4 gap-2"><select defaultValue={l.assigned_sales_id??''} onChange={async e=>{await fetch('/api/department/leads',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({leadId:l.id,action:'sales_assign',employeeId:e.target.value})});load()}} className="border rounded-lg p-2 text-xs"><option value="">Assign sales employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select><input defaultValue={l.follow_up_date?new Date(l.follow_up_date).toISOString().slice(0,16):''} type="datetime-local" className="border rounded-lg p-2 text-xs" onBlur={e=>save(l.id,{followUpDate:e.target.value?new Date(e.target.value).toISOString():null})}/><input defaultValue={l.call_scheduled_at?new Date(l.call_scheduled_at).toISOString().slice(0,16):''} type="datetime-local" className="border rounded-lg p-2 text-xs" onBlur={e=>save(l.id,{callScheduledAt:e.target.value?new Date(e.target.value).toISOString():null})}/><select defaultValue={l.status} className="border rounded-lg p-2 text-xs" onChange={e=>save(l.id,{status:e.target.value})}><option>Assigned To Sales</option><option>Contacted</option><option>Proposal</option><option>Negotiation</option><option>Won</option><option>Lost</option></select></div><textarea defaultValue={l.sales_notes??''} placeholder="Interaction notes" className="w-full border rounded-lg p-3 text-sm" onBlur={e=>save(l.id,{notes:e.target.value})}/>{saving===l.id&&<span className="text-xs text-slate-500">Saving…</span>}</article>)}</div>}</section></main>;
}
