import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { canAccessDepartment, getAuthContext, isDepartmentHead } from '@/lib/department-auth';
export async function GET(request: Request) {
 const ctx=await getAuthContext(); if(!ctx.employeeId&&!ctx.isAdmin)return NextResponse.json({error:'Unauthorized'},{status:401}); const p=new URL(request.url).searchParams; const department=p.get('department')??ctx.department;
 if(!department||!canAccessDepartment(ctx,department as never))return NextResponse.json({error:'Forbidden'},{status:403}); let q=supabase.from('department_tasks').select('*,assigned_employee:employees(id,first_name,last_name,email),lead:leads(id,name,company,email)').eq('department',department).order('scheduled_at');
 if(p.get('employeeId'))q=q.eq('assigned_to',p.get('employeeId')); else if(!ctx.isAdmin&&!isDepartmentHead(ctx))q=q.eq('assigned_to',ctx.employeeId); if(p.get('completed')==='false')q=q.eq('is_completed',false);
 const {data,error}=await q;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({data});
}
export async function POST(request:Request){const ctx=await getAuthContext();if(!ctx.employeeId&&!ctx.isAdmin)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await request.json();const department=b.department??ctx.department;if(!department||!canAccessDepartment(ctx,department as never))return NextResponse.json({error:'Forbidden'},{status:403});if(!isDepartmentHead(ctx)&&b.assignedTo&&b.assignedTo!==ctx.employeeId)return NextResponse.json({error:'Employees can only assign tasks to themselves'},{status:403});const assignedTo=b.assignedTo??ctx.employeeId;const {data,error}=await supabase.from('department_tasks').insert({title:b.title,description:b.description??null,department,assigned_to:assignedTo,lead_id:b.leadId??null,scheduled_at:b.scheduledAt}).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({success:true,data},{status:201});}
export async function PATCH(request:Request){const ctx=await getAuthContext();if(!ctx.employeeId&&!ctx.isAdmin)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await request.json();if(!b.taskId)return NextResponse.json({error:'taskId is required'},{status:400});const {data:task}=await supabase.from('department_tasks').select('*').eq('id',b.taskId).single();if(!task||!canAccessDepartment(ctx,task.department as never))return NextResponse.json({error:'Forbidden'},{status:403});if(!isDepartmentHead(ctx)&&task.assigned_to!==ctx.employeeId)return NextResponse.json({error:'You can only update your assigned tasks'},{status:403});const u:Record<string,unknown>={};for(const k of ['title','description','lead_id','scheduled_at','is_completed'])if(b[k]!==undefined)u[k]=b[k];if(b.assigned_to!==undefined){if(!isDepartmentHead(ctx)&&b.assigned_to!==ctx.employeeId)return NextResponse.json({error:'You cannot reassign this task'},{status:403});u.assigned_to=b.assigned_to;}const {data,error}=await supabase.from('department_tasks').update(u).eq('id',b.taskId).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({success:true,data});}
